env:
  global:
  - REPO=haoye/portal_ds

sudo: required
warnings_are_errors: false
language: generic

services:
  - docker

before_install:
  # copy environmental variables to a file
  - env > env_file

  # retrieve the docker container from docker hub
  - docker pull $REPO

  # run the docker container and copy over the files into the container
  - docker run --env-file env_file --name portalds -t -d $REPO /bin/bash
  - docker exec -i portalds bash -c "rm -fr /portalDS"
  - docker cp ../portalDS portalds:/

script:
  # navigate into the directory and run devtools::check on the package
  - docker exec -i portalds bash -c "cd portalDS && Rscript -e 'devtools::check()'"

after_success:
  - docker exec -i portalds bash -c "R CMD INSTALL portalDS"
  - docker exec -i portalds bash -c "cd portalDS && Rscript -e 'pkgdown::build_site()'"
  - docker exec -i portalds bash -c "cd portalDS && Rscript -e 'covr::codecov()'"
  
  