env:
  global:
  - REPO=$DOCKER_USER/portal_ds

sudo: required
warnings_are_errors: false
language: generic

services:
  - docker

before_install:
  # retrieve the docker container from docker hub
  - docker pull $REPO

  # run the docker container and copy over the files into the container
  - docker run --name portalds -t -d $REPO /bin/bash
  - docker cp ../portalDS portalds:/

script:
  # navigate into the directory and run devtools::check on the package
  - docker exec -i portalds bash -c "cd portalDS && Rscript -e 'devtools::check()'"

after_success:
