language: r
cache: packages
sudo: required
dist: "xenial"
warnings_are_errors: false

r_check_args: "--no-vignettes"

r_packages:
  - covr

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
    update: true

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
        